# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45521d62a7b56485f89c062d89402bf1662d966238df87fc09e8a862175c5aa4f4eaa82553316ddaadb2a9e1ce59da0f9ac1cfabf0d0a49268ae954cee346231

test:
  secret_key_base: f9aae71ad76ca93e95cf42ded5f72392dacb98e1cbf2f6c5c1336ab0a36762402a02c3b07d599b90f722a374b7528068876bd5684a78d23fda408b079f894b9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
